import { createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    primitive: {
      slate: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
      violet: {
        50: null,
        100: null,
        200: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
        950: null,
      },
      emerald: {
        50: null,
        100: null,
        300: null,
        400: null,
        500: null,
        600: null,
        800: null,
        900: null,
      },
      rose: {
        50: null,
        300: null,
        400: null,
        500: null,
        600: null,
        800: null,
        950: null,
      },
      amber: {
        100: null,
        300: null,
        400: null,
        500: null,
        600: null,
        700: null,
        800: null,
        900: null,
      },
    },
    semantic: {
      brand: {
        primary: null,
        primaryHover: null,
        primaryActive: null,
        accent: null,
        accentHover: null,
        accentActive: null,
        containerLight: null,
      },
      background: {
        base: null,
        content: null,
        subtle: null,
        muted: null,
        elevated: null,
        popup: null,
        sidebar: null,
        greyFill: null,
        hover: null,
        selected: null,
        disabled: null,
        tag: null,
        overlay: null,
      },
      foreground: {
        primary: null,
        secondary: null,
        tertiary: null,
        muted: null,
        disabled: null,
        onBrand: null,
        accent: null,
        link: null,
        linkHover: null,
      },
      border: {
        default: null,
        strong: null,
        subtle: null,
        accent: null,
        hover: null,
        line: null,
      },
      success: {
        base: null,
        main: null,
        hover: null,
        subtle: null,
        background: null,
        text: null,
        border: null,
      },
      error: {
        base: null,
        main: null,
        hover: null,
        subtle: null,
        containerLight: null,
        text: null,
        border: null,
      },
      warning: {
        base: null,
        main: null,
        hover: null,
        subtle: null,
        background: null,
        text: null,
        border: null,
      },
      highlight: {
        background: null,
        border: null,
      },
      added: {
        background: null,
        subtleBackground: null,
      },
      code: {
        base: null,
        comment: null,
        keyword: null,
        string: null,
        attribute: null,
        addition: null,
        deletion: null,
        tagBackground: null,
        tagColor: null,
      },
    },
  },
  gradient: {
    background: {
      subtle: null,
      muted: null,
      warm: null,
    },
    brand: {
      primary: null,
      accent: null,
      hero: null,
      subtle: null,
    },
    overlay: {
      dark: null,
      light: null,
    },
    mesh: {
      warm: null,
      subtle: null,
    },
    shimmer: {
      violet: null,
      light: null,
    },
    text: {
      violet: null,
      subtle: null,
      hero: null,
    },
    success: {
      subtle: null,
      base: null,
    },
    error: {
      subtle: null,
      base: null,
    },
    warning: {
      subtle: null,
      base: null,
    },
  },
  space: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    8: null,
    10: null,
    12: null,
    16: null,
    20: null,
    24: null,
    32: null,
  },
  shadow: {
    none: null,
    sm: null,
    base: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    inner: null,
  },
  radius: {
    none: null,
    sm: null,
    base: null,
    md: null,
    lg: null,
    xl: null,
    '2xl': null,
    '3xl': null,
    full: null,
  },
  transition: {
    duration: {
      fast: null,
      base: null,
      slow: null,
      slower: null,
    },
    easing: {
      linear: null,
      in: null,
      out: null,
      inOut: null,
    },
  },
});
